const imageRole ={
  2: require('./images/UpgradeAcc_Edit_Per.png'),
  3: require('./images/UpgradeAcc_Tho.png'),
  4: require('./images/UpgradeAcc_NX.png'),
  5: require('./images/UpgradeAcc_NBS.png'),
  6: require('./images/UpgradeAcc_SV.png'),
}
const images = {
  getStarted1: require('./images/GetStarted_1.png'),
  getStarted2: require('./images/GetStarted_2.png'),
  getStarted3: require('./images/GetStarted_3.png'),
  logo: require('./images/Logo.png'),
  left_or: require('./images/Left-or.png'),
  right_or: require('./images/Right-or.png'),
  backgroungHG: require('./images/backgroundHG.jpg'),
  imageRole,
  ic_money: require('./images/ic_money.png'),
  ic_check: require('./images/ic_check.png'),
  bg_image1: require('./images/bg_image1.jpg'),
  bg_image2: require('./images/bg_image2.jpg'),
  bg_voucher: require('./images/bg_voucher.jpg'),
  add_imgSV: require('./images/add_IMG.png'),
  bg_cannot_connect: require('./images/bg_cannot_connect.png'),
  ic_introduce: require('./images/ic_introduce.png'),
  ic_notifi: require('./images/ic_notifi.png'),
  ic_image: require('./images/ic_image.png'),
  ic_expired: require('./images/ic_expired.png'),
  icon_notifi: require('./images/icon_notification.png'),
  ic_person: require('./images/ic_person.png'),
  ic_link: require('./images/ic_link.png'),
  ic_gift: require('./images/ic_gift.png'),
  ic_star: require('./images/ic_star.png'),
  ic_file: require('./images/ic_file.png'),
  ic_list: require('./images/ic_list.png'),
  ic_lociation: require('./images/ic_lociation.png'),
  ic_select: require('./images/ic_select.png'),
  ic_video: require('./images/ic_video.png'),
  ic_down_slider: require('./images/ic_down_slider.png'),
  ic_up_slider: require('./images/ic_up_slider.png'),
  ic_pen_edit: require('./images/ic_pen_edit.png'),
  ic_trash: require('./images/ic_trash.png'),
  img_slider_info: require('./images/img_slider_info.png'),
  bg_person: require('./images/bg_person.jpg'),
  ic_signin: require('./images/ic_signIn.png'),
  ic_candidate_marker: require('./images/ic_candidate_marker.png'),
  ic_thanks_you: require('./images/ic_thanks_you.png'),
  ic_upload_video: require('./images/img_upload_video.png'),
  ic_show_video: require('./images/ic_show_video.png'),
  bg_star: require('./images/bg_star.png'),
}

export default images