export const LOGGING_IN = 'LOGGING_IN';
export const LOGGING_IN_SUCCESS = 'LOGGING_IN_SUCCESS';
export const LOGGING_IN_FAILED = 'LOGGING_IN_FAILED';

export const QRSCANNER_TEXT = 'QRSCANNER_TEXT';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const RESET_VALUE_SIGN_UP = 'RESET_VALUE_SIGN_UP';

export const CHECK_LOGGING_IN_SOCIAL = 'CHECK_LOGGING_IN_SOCIAL';
export const CHECK_LOGGING_IN_SOCIAL_SUCCESS = 'CHECK_LOGGING_IN_SOCIAL_SUCCESS';
export const CHECK_LOGGING_IN_SOCIAL_FAILED = 'CHECK_LOGGING_IN_SOCIAL_FAILED';

export const LOGGING_IN_SOCIAL = 'LOGGING_IN_SOCIAL';
export const LOGGING_IN_SOCIAL_SUCCESS = 'LOGGING_IN_SOCIAL_SUCCESS';
export const LOGGING_IN_SOCIAL_FAILED = 'LOGGING_IN_SOCIAL_FAILED';

export const UPDATING_PHONE = 'UPDATING_PHONE';
export const UPDATING_PHONE_SUCCESS = 'UPDATING_PHONE_SUCCESS';
export const UPDATING_PHONE_FAILED = 'UPDATING_PHONE_FAILED';
export const LOCATION_UPDATED = 'LOCATION_UPDATED';
export const UPDATING_USER = 'UPDATING_USER';
export const RESET_VALUE_USER = 'RESET_VALUE_USER';
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
export const FETCHING_USER_FAILED = 'FETCHING_USER_FAILED';


export const RELOAD_SAVE = 'RELOAD_SAVE';
