# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoiThatHG' do

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for NoiThatHG

  pod 'Firebase/Auth', '~> 5.11.0'
pod 'GoogleSignIn'
pod 'Firebase/Core'
pod 'GoogleMaps'
pod 'GooglePlaces'
  pod 'GooglePlacePicker'

  target 'NoiThatHGTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NoiThatHG-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NoiThatHG-tvOS

  target 'NoiThatHG-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
